version: "3"
services:
  zookeper-saga:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeper-saga
    environment:
      ZOOKEPER_CLIENT_PORT: 2181
      ZOOKEPER_TICK_TIME: 2000

  broker-saga:
    image: confluentinc/cp-kafka:7.6.0
    container_name: broker-saga
    ports:
      - "9092:9092"
    depends_on:
      - zookeper-saga
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEPER_CONNECT: "zookeper-saga:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT,PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker-saga:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
